name: Build

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

env:
  PUBLIC_NAME: Umbra
  SOLUTION_NAME: Umbra
  INTERNAL_NAME: Umbra
  RELEASE_DIR: out/Release
  PERSONAL_PLUGIN_REPO: una-xiv/umbra-dist

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"
      - name: Build
        run: |
          dotnet restore -r win ${{ env.SOLUTION_NAME }}.sln
          dotnet build --configuration Release
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: true
      - uses: actions/upload-artifact@v4
        with:
          name: UmbraDistZip
          path: ${{ env.RELEASE_DIR }}
          if-no-files-found: error

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ env.PERSONAL_PLUGIN_REPO }}
          token: ${{ secrets.PAT }}
      - uses: actions/download-artifact@v4
        with:
          name: UmbraDistZip
          path: dist
      - uses: EndBug/add-and-commit@v7
        with:
          branch: main
          add: --all
          author_name: GitHub Action
          author_email: github-actions[bot]@users.noreply.github.com
          message: Update ${{ env.INTERNAL_NAME }} ${{ github.ref_name }}
